# goqty

Goqty is a Go port of gentooboontoo's js-quantities Javascript library (https://github.com/gentooboontoo/js-quantities) which is a port of Kevin Olbrich's Ruby library
Units (https://github.com/olbrich/ruby-units).

The library aims to simplify the handling of units for scientific calculations involving quantities.

This library has no dependencies.

## Installation

go get github.com/wjanssens/goqty

## Usage

[source,go]
----
import (
    "fmt"
    "github.com/wjanssens/goqty"
)
if q, err := qty.Parse("50km/h"); err == nil {
    fmt.Printf("%v\n", q) // => 50 km/h
}
----

## Synopsis

.Creation
[source,go]
----
qty, err = Parse("1m");
qty, err = Parse('m'); // scalar defaults to 1

// compound numerators
qty, err = Parse("1 N*m");
qty, err = Parse("1 N m"); // * is optional

// denominators
qty, err = Parse("1 m/s");

// powers
qty, err = Parse("1 m^2/s**2"); // ^ or **
qty, err = Parse("1 m^2 s^-2"); // negative powers
qty, err = Parse("1 m2 s-2"); // ^ is optional

qty, err = Parse("1 m^2 kg^2 J^2/s^2 A");

// unitless quantities
qty, err = Parse("1.5");
qty, err = New(1.5, "");

// unicode prefixes and units
qty, err = Parse("1.5 µm");
qty, err = Parse("1.5 Ω");

qty = Qty("1 attoparsec/microfortnight");
----

.Properties
[source,go]
----
c := a.Scalar()         // returns the scalar of a quantity (10 m => 10)
u := a.Units()          // returns the units of a quantity (10 m => m)
k := a.Kind()           // returns the kind of a quantity (10 m => length)
----

.Predicates
[source,go]
----
t := a.IsInverse(b)     // true if quantities are the inverse of each other
t := a.IsCompatible(b)  // true if quantities have the same kind
t := a.IsUnitless()     // true if quantity has no units
t := a.IsBase()         // true if quantity is represented with base units
----

.Conversion
[source,go]
----
c, err := a.To('m')      // returns a scaled quantity (0.1 m => 10 cm)
c, err := a.To('S')      // returns an inverted quantity (10 ohm => .1 S)
c, err := a.ToBase()     // returns a quantity in SI units (10 cm => 0.1 m)
c, err := a.ToFloat()    // returns the scalar of a unitless quantity
c, err := a.Inverse()    // returns an interned quantity (100 m/s => .01 s/m; 10 ohm => .1 /ohm, not .1 S)
----

.Swift Conversion
[source,go]
----
converter := qty.SwiftConverter("m/h", "ft/s")
converted, err := converter([]float64{2500, 5000})        // []float64{2.278, 4.556}
----

.Comparison
[source,go]
----
// quantities with compatible quantities can be compared
eq, err := a.Eq(b)          // true if both quantities are equal (1m == 100cm => true)
same, err := a.Same(b)      // true if both quantities are same (1m == 100cm => false)
lt, err := a.Lt(b)          // true if a is stricty less than b
lte, err := a.Lte(b)        // true if a is less than or equal to b
gt, err := a.Gt(b)          // true if a is stricty greater than b
gte, err := a.Gte(b)        // true if a is greater than or equal to b
v, err := a.compareTo(b);   // -1 if a < b, 0 if a == b, 1 if a > b
----

.Operators
[source,go]
----
// quantities with compatible quantities can be added and substracted
c, err := a.Add(b)          // 2.5 m + 3 cm => 2.53 m ; 3 cm + 2.5 m => 253 cm
c, err := a.Sub(b)          // 2.5 m - 3 cm => 2.47 m ; 3 cm - 2.5 m => -247 cm
// any quantities can be multiplied and divided (excluding temperatures)
c, err := a.Mul(b)          // 2.5 m * 3 cm => 0.075 m^2 ; 3 cm * 2.5 m => 750 cm^2
c, err := a.Div(b)          // 7.5 degF / 2.5 m^2 => 3 °F/m^2
----

.Rounding
[source,go]
----
q, _ := qty.Parse("5.17 ft")
q.ToPrec("ft");             // => 5 ft
q.ToPrec("0.5 ft");         // => 5 ft
q.ToPrec("0.25 ft");        // => 5.25 ft
q.ToPrec("0.1 ft");         // => 5.2 ft
q.ToPrec("0.05 ft");        // => 5.15 ft
q.ToPrec("0.01 ft");        // => 5.17 ft
q.ToPrec("0.00001 ft");     // => 5.17 ft
q.ToPrec("2 ft");           // => 6 ft
q.ToPrec("2");              // => 6 ft

q, _ = qty.Parse("6.3782 m");
q.ToPrec("dm");             // => 6.4 m
q.ToPrec("cm");             // => 6.38 m
q.ToPrec("mm");             // => 6.378 m
q.ToPrec("5 cm");           // => 6.4 m
q.ToPrec("10 m");           // => 10 m
qty.ToPrec(0.1);            // => 6.3 m

q, _ = qty.Parse("1.146 MPa");
q.ToPrec("0.1 bar");        // => 1.15 MPa
----

.Formatting
[source,go]
----
// String() can be used to get the cannonical representation of the quantity, which can always be parsed
q.String()                     // 1.146 MPa => "1.146 MPa"
q.Format(qty.DefaultFormatter) // 1.146 MPa => "1.146 MPa"

fn := func(scalar float64, unit string) string {
    v := number.Decimal(scalar, number.MaxIntegerDigits(4), number.MinIntegerDigits(2))
    return message.NewPrinter(language.Dutch).Sprintf("%v %v", v, unit)
}
f := q.Format(fn)               // 2.987654321 m => 02,988 m
----

.Temperature
qoqty makes a distinction between a temperature and degrees of a temperature.
Temperature units (eg tempC) can be converted back and forth, and will take into account the differences in the zero points of the various scales.  Differential temperature degree (eg degC) units behave like most other units.
It is an error to create a temperature below absolute zero.
Math with temperatures is fairly limited.
[source,go]
----
t100, _ := qty.Parse("100 tempC")
t100.Add("10 degC")             // 110 tempC; temp + deg is always safe 
t100.Sub("10 degC")             // 90 tempC;  temp - deg is always safe
t100.Add("50 tempC")            // error; can't add two temperatures
t100.Sub("50 tempC")            // 50 °C
t100.Sub("150 tempC")           // -50 °C
t100.Mul(2)                     // 200 tempC
t100.Div(2)                     // 50 tempC
t100.Inverse()                  // error
t100.Mul(qty)                   // error
t100.Div(qty)                   // error
qty.Parse("100 tempC*unit")     // error
qty.Parse("100 tempC/unit")     // error
qty.Parse("100 unit/tempC")     // error
t100.To("degC")                 // 100 °C; references the 0 point on the scale of the temperature unit

d100, _ := qty.Parse("100 degC")
d100.To("tempC")                // -173.15 tempC; interpreted as being relative to absolute zero
----

.Kinds and Units
[source,go]
----
k := qty.Kinds()            // a list of kinds of units (length, area, volume, time, ...)
u := qty.Units("length")    // a list of units of a kind (meter, inch, foot, mile, ...)
a := qty.Aliases("m")       // a list of unit aliases (m, meter, meters, metre, metres)
----

## Contribute

Feedback and contributions are welcomed.

Pull requests must pass tests. Please make sure that `go test` returns no errors before submitting.